# Base config
# for loading characters, the pattern is name=type
# possible types are: adventurer, boss, monster, player

[InitialHeroes]
Nadia Cardigan=adventurer
Elias Shlongue=player
Aurelia=player
Shabi Zovalt=player
Pafnucy=player

[InitialEnemies]
