# Base config
# for loading characters, the pattern is name=type
# possible types are: mob, npc, boss, player

[InitialHeroes]
Elias Shlongue=player
Aurelia=player
Shabi Zovalt=player
Pafnucy=player
Nadia Cardigan=npc
Tanissa Beifina=npc
Raza=npc

[InitialEnemies]
(Czerwone Szale) Strzelec=mob
(Czerwone Szale) Bard=mob
(Czerwone Szale) Łotr=mob
(Czerwone Szale) Byk=mob
(Czerwone Szale) Snajper=mob
(Czerwone Szale) Herszt=boss